[package]
name = "amanita-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
fast_rsync = "0.2.0"
log = "0.4.20"
serde = { version = "1.0.190", features = ["derive"] }
